### ISSUE TITLE
Testing in webpack workflow

### ISSUE THREAD

**Issue by iGitScor** [iGitScor/webpack-content-replacer-plugin#17]
Hello contributors,

The plugin is test covered as unit library.
We should add test in a webpack workflow.

## Contribution

- Creation of a demo webpack build (1 html file, 1 css file)
- Use of this [plugin](https://github.com/iGitScor/webpack-content-replacer-plugin)
- Test the webpack build (_the plugin result_)

**Comment by YQBird** [comment]
Hi iGitScor, I come from Twitter #Your First PR and want to start contributing to open source project. If would be great if you could give me some instruction here, like where to start or what to test. Thanks!

**Comment by iGitScor** [comment]
Welcome @YQBird,

Thank you for your interest on this project. I have several projects, plugins, web apps, ... and I am a member of a passionate team which look after contributors. So I hope you'll find a project you'll love contribute to.

For this project, the aim is to have a webpack plugin which allow to replace content in any file in the project in webpack step (done, after-emit and error)

This issue would permit to be sure that the plugin works well in webpack 1 and potentially webpack 2

## Todo list

- Create a folder with a webpack config file, an HTML file and a css one
- Create a test case for the code coverage to check the plugin in the webpack workflow

If you need more details or any help, do not hesite !
And if you want to participate to other project (after this), it will be great

Thank you

**Comment by YQBird** [comment]
@iGitScor. Thank you so much for the help here. I will start working on this today and I will keep you posted for the update. This would be a great start for me. :)

**Comment by YQBird** [comment]
Hi @iGitScor. How can I push my branch to Github for this repository? I got unauthorized 403 status code when trying to push my commits.
Thanks

**Comment by iGitScor** [comment]
Hi @YQBird, 

I'm sorry, I didn't explain you how to contribute to an open source project on Github.

- To add code to this plugin, you have to [fork the repository](https://help.github.com/articles/fork-a-repo/)

- After that, you'll work on your copy for each modifications so you have to clone your fork, make some development, then push it to your repository YQBird/webpack-content-replacer-plugin

- When you think the development is over, you have to [make a pull request](https://help.github.com/articles/creating-a-pull-request/)

If you are blocked at some step, please ask me some questions

**Comment by iGitScor** [comment]
@YQBird, do want to work on another project ? Or do you want to improve this project ? I have several ideas, I can create issues for them

**Comment by YQBird** [comment]
@iGitScor, both sounds good for me. I don't have any preference. Please let me know when you create the issue. Thanks!

**Comment by iGitScor** [comment]
Hi @YQBird, please tell me what kind of work are you looking for ?

For now, created issues for this project are mainly documentation
https://github.com/iGitScor/webpack-content-replacer-plugin/issues 

You can also look another similar project I've just started
https://github.com/iGitScor/critical-webpack-plugin/issues

I have also a fourth plugin I would like to start coding, if you want to be involved, we can get in touch (and after that why not adding you as maintainer with more rights) 

Thank you very much

**Comment by YQBird** [comment]
@iGitScor. I will check what I can help with current project(content replacer) tonight. I would like to involved in your new project as well. Thanks!
