### ISSUE TITLE
Rename plugin class

### ISSUE THREAD

**Issue by iGitScor** [iGitScor/webpack-content-replacer-plugin#21]
Hi,

According to Webpack team:
> 3rd party Plugin names should be foo-webpack-plugin for pkg name and FooWebpackPlugin for class

The package will not be renamed for now but we have to change plugin class.
It should keep compatibility with previous class name.

## Task list

- [x] Change documentation
- [x] Update test case
- [x] Update class name

If you find another side effect, do not hesitate to correct it

Thank you

**Comment by Phinneas** [comment]
If you are still looking for a contributor for this I would love to help out. I found this through Twitter Your First PR.

**Comment by iGitScor** [comment]
Hi @Phinneas,

Thank you for helping us !
Of course, I always looking for project contributors. For this issue, nobody has started to work on, so, please feel free to make a pull request with your enhancement :wink:

I hope we'll work together on great stuffs !

Welcome

**Comment by iGitScor** [comment]
Hi @Phinneas,

do you need some help ?

**Comment by Phinneas** [comment]
I may. I'm entry level to coding but I want to refine my chops beyond just class work. And to be honest I have, as of yet, had much time to work on this. If you give me hint on how to start I can take it from there.  

Open sesame.

**Comment by iGitScor** [comment]
Hi,

I'm glad to hear that you're a "student" and you already want to contribute to help the community ❤️ 

So, I'll give you some tricks to resolve this issue.
For now, we have `class ContentReplacer` in the [index.js file](https://github.com/iGitScor/webpack-content-replacer-plugin/blob/master/index.js)

We need to have a class name `ContentReplacerWebpackPlugin` so you can easily change class name.

You have to replace all constructor in [tests](https://github.com/iGitScor/webpack-content-replacer-plugin/tree/master/test)

After that, make a commit, a pull request and I'll give you more advice to complete the issue

Thank you very much @Phinneas

**Comment by Phinneas** [comment]
Sweet. thank you
