### ISSUE TITLE
Test the done and failed steps

### ISSUE THREAD

**Issue by iGitScor** [iGitScor/webpack-content-replacer-plugin#38]
Hi,

_Request a feature_

**What is the current behavior?**

_The current plugin is not tested in the webpack workflow for` done` and `failed` steps_

**What is the expected behavior?**

_The plugin can be launched at `done`and `failed`step_

Thank you !

**Comment by Phinneas** [comment]
I would like to take a crack at this one.

**Comment by iGitScor** [comment]
Hi @Phinneas,

I'm already working on it but if you want to make a proposal to compare, feel free 😉
